# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fmi3.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfmi3.proto\x12\x05proto\"\x07\n\x05\x45mpty\"\x17\n\x08Instance\x12\x0b\n\x03key\x18\x01 \x01(\x05\"9\n\x11getValue64Request\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x17\n\x0fvalueReferences\x18\x02 \x03(\x05\"!\n\x0fgetFloat64Reply\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x98\x01\n\x1e\x65nterInitializationModeRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x10toleranceDefined\x18\x02 \x01(\x08\x12\x11\n\ttolerance\x18\x03 \x01(\x01\x12\x11\n\tstartTime\x18\x04 \x01(\x01\x12\x17\n\x0fstopTimeDefined\x18\x05 \x01(\x08\x12\x10\n\x08stopTime\x18\x06 \x01(\x01\"^\n\rdoStepRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x19\x63urrentCommunicationPoint\x18\x02 \x01(\x01\x12\x1d\n\x15\x63ommunicationStepSize\x18\x03 \x01(\x01\"\x17\n\x05\x41rray\x12\x0e\n\x06values\x18\x01 \x03(\x01\x32\x86\x04\n\x04\x66mi3\x12:\n\x17instantiateCoSimulation\x12\x0c.proto.Empty\x1a\x0f.proto.Instance\"\x00\x12/\n\x0c\x66reeInstance\x12\x0f.proto.Instance\x1a\x0c.proto.Empty\"\x00\x12)\n\x06\x64oStep\x12\x0f.proto.Instance\x1a\x0c.proto.Empty\"\x00\x12\x36\n\x13getContinuousStates\x12\x0f.proto.Instance\x1a\x0c.proto.Array\"\x00\x12\x31\n\x0egetDerivatives\x12\x0f.proto.Instance\x1a\x0c.proto.Array\"\x00\x12P\n\x17\x65nterInitializationMode\x12%.proto.enterInitializationModeRequest\x1a\x0c.proto.Empty\"\x00\x12\x39\n\x16\x65xitInitializationMode\x12\x0f.proto.Instance\x1a\x0c.proto.Empty\"\x00\x12@\n\ngetFloat64\x12\x18.proto.getValue64Request\x1a\x16.proto.getFloat64Reply\"\x00\x12,\n\tterminate\x12\x0f.proto.Instance\x1a\x0c.proto.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fmi3_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=21
  _globals['_EMPTY']._serialized_end=28
  _globals['_INSTANCE']._serialized_start=30
  _globals['_INSTANCE']._serialized_end=53
  _globals['_GETVALUE64REQUEST']._serialized_start=55
  _globals['_GETVALUE64REQUEST']._serialized_end=112
  _globals['_GETFLOAT64REPLY']._serialized_start=114
  _globals['_GETFLOAT64REPLY']._serialized_end=147
  _globals['_ENTERINITIALIZATIONMODEREQUEST']._serialized_start=150
  _globals['_ENTERINITIALIZATIONMODEREQUEST']._serialized_end=302
  _globals['_DOSTEPREQUEST']._serialized_start=304
  _globals['_DOSTEPREQUEST']._serialized_end=398
  _globals['_ARRAY']._serialized_start=400
  _globals['_ARRAY']._serialized_end=423
  _globals['_FMI3']._serialized_start=426
  _globals['_FMI3']._serialized_end=944
# @@protoc_insertion_point(module_scope)
