name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag DevContainer image
        run: |
          docker build -t my-devcontainer-image .devcontainer

      - name: Run DevContainer and build project
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-devcontainer-image \
          bash -c "mkdir -p build && cd build && cmake .. && make"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v21
        with:
          files: build/liaison